{% set version = "0.51.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rastervis
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rasterVis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rasterVis/rasterVis_{{ version }}.tar.gz
  sha256: 61bd0d19d045b50c6764f3a7c95ce1e734af9e5f964449825d002afe02109489

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcolorbrewer
    - r-hexbin
    - r-lattice >=0.20_41
    - r-latticeextra
    - r-raster >=2.0_12
    - r-sp >=1.0_6
    - r-terra
    - r-viridislite
    - r-zoo
  run:
    - r-base
    - r-rcolorbrewer
    - r-hexbin
    - r-lattice >=0.20_41
    - r-latticeextra
    - r-raster >=2.0_12
    - r-sp >=1.0_6
    - r-terra
    - r-viridislite
    - r-zoo

test:
  commands:
    - $R -e "library('rasterVis')"           # [not win]
    - "\"%R%\" -e \"library('rasterVis')\""  # [win]

about:
  home: http://oscarperpinan.github.io/rastervis
  license: GPL-3.0-only
  summary: Methods for enhanced visualization and interaction with raster data. It implements visualization methods for quantitative data and categorical data, both for univariate and multivariate rasters. It also provides methods to display spatiotemporal rasters, and vector fields. See the website for examples.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: rasterVis
# Type: Package
# Title: Visualization Methods for Raster Data
# Version: 0.46
# Encoding: UTF-8
# Authors@R: c(person("Oscar", "Perpinan Lamigueiro", email="oscar.perpinan@gmail.com", role=c('cre', 'aut'), comment = c(ORCID = "0000-0002-4134-7196")), person("Robert", "Hijmans", email= "r.hijmans@gmail.com", role='aut'))
# Description: Methods for enhanced visualization and interaction with raster data. It implements visualization methods for quantitative data and categorical data, both for univariate and multivariate rasters. It also provides methods to display spatiotemporal rasters, and vector fields. See the website for examples.
# URL: http://oscarperpinan.github.io/rastervis
# BugReports: https://github.com/oscarperpinan/rastervis/issues
# License: GPL-3
# LazyLoad: yes
# Depends: R (>= 2.14.0), methods, raster (>= 2.0-12), lattice, latticeExtra
# Imports: stats, utils, parallel, grid, grDevices, RColorBrewer, hexbin, sp (>= 1.0-6), zoo, viridisLite
# Suggests: rgl, ggplot2, colorspace, dichromat
# NeedsCompilation: no
# Packaged: 2019-07-02 13:53:25 UTC; oscar
# Author: Oscar Perpinan Lamigueiro [cre, aut] (<https://orcid.org/0000-0002-4134-7196>), Robert Hijmans [aut]
# Maintainer: Oscar Perpinan Lamigueiro <oscar.perpinan@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-07-02 16:00:10 UTC
