{% set version = "0.44" %}

package:
  name: r-rastervis
  version: {{ version }}

source:
  fn: rasterVis_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rasterVis_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rasterVis/rasterVis_{{ version }}.tar.gz
  sha256: b0272e71e3f12916131ab87ab1a96cc9520d0eb3c25552b1814a6fb64d1b2a10

build:
  number: 0
  skip: True  # [win32]
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-rcolorbrewer
    - r-hexbin
    - r-lattice
    - r-latticeextra
    - r-raster >=2.0_12
    - r-sp >=1.0_6
    - r-viridislite
    - r-zoo
  run:
    - r-base
    - r-rcolorbrewer
    - r-hexbin
    - r-lattice
    - r-latticeextra
    - r-raster >=2.0_12
    - r-sp >=1.0_6
    - r-viridislite
    - r-zoo

test:
  commands:
    - $R -e "library('rasterVis')"  # [not win]
    - "\"%R%\" -e \"library('rasterVis')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/rasterVis
  license: GPL-3
  summary: Methods for enhanced visualization and interaction with raster data. It implements
    visualization methods for quantitative data and categorical data, both for univariate
    and multivariate rasters. It also provides methods to display spatiotemporal rasters,
    and vector fields. See the website for examples.

extra:
  recipe-maintainers:
    - ocefpaf
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
