appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: AhQwWh35S2ZTYds9RrLFPd8lstJ7QGjvwv3z9KRIH5D3CaPLlRIgdaWNAn/+oPRq0o/Lr22aIs3qI+8MTqZtmwnQCbgi/jspjItQ+7oxS5ZvML2L9wbf1d44EawmMGaPRyGF9r2g0Gn4wJCMTjsG+gkRuHtDbH5zCb0K6gYBmRidU9+LS00lN1WHukLxNaJtbEHmsge270JYrNrui1Sx1LG3ggrMZPngcVGwSFUz3U1YTKxdzPPduat+iLw5BxBOo0dFeVZp0o0OUFetZALbipA+Q0Mu+yRep24N1g2qxOtYFjJtHRvGza2P1GNs+cHkS0qBZjgcvNg0O+sJNyGT+8wS6VPtb80zbleIF2Cv69juwJBck9P2HeZ0ZaDV+aSRVcrV4zsmP+wbWg+aBsnq6PTIkJ3qGDBGVsXP3IMBqWrKPMaOGWvy7FnLoBN5pP7g+1RqvDJdFSfAYJ+1XkziiGg0zPOOrDyPlcPaniQGZRyNhOXmnOPj4DDcw8o0xZ9ZgNryfxUFSIDJqt9C+qNHVPb89ZCvLp8qt+6eeXB7XjxMCYsK8fuNrD5N9bHFe4Eosbaah8+uTVbZfbg6Wu351h9GQ3rJQMTdJl4G4oBoTMIPWzsUTgHcGJWbGAomAfJb4uC9qSCgVipZADglDbjbop0qkiHdV7ACIyqwA47i5WU=
conda_forge_output_validation: true
