travis:
  secure:
    BINSTAR_TOKEN: EhIUZ3KRCSvD5IMe9vdWLFohmN+uoGgT6FQtVbPZqGq/aw+Jaxn5E5KWFQMQh57ydrbZcdzHrdmt3pK1AXO4eRBWDp04n6zxvJRrku+92X03gTgQJQOJGI0CvZ0T6aiwekmIDLhPV2bMKwL2im5BdlEG771z/wDZNleyxIuNyQTJim1CXNHkytLwpByf3JcwaZL2OyCY5/WyvJkzA4XLe2rRv3Rdlju2Bzol60/uySHvUYB50nJjdaaGM5Y+dWIkY6vrZ//ZGHHvXSxVs8qutwclBx/tDSW0uJTMDAKNcrLOcTW24jqCNhKMFz5fC/znK+knNYor8hRs9x3smic/s4NIHCA9Jco+dccQemYIL75Ajes7gLrmBeYKiuaFqF9TfYYitBt5LLwpPvpJBwws4KK33/5i1RwzQFMJhAhV/z7TqdWKz1RYXmt4qbHhlvYEy4Q+X7YQWxgm2Abvnope3+raSRDsRWDPsbmR8fEw0NAUeSt9nNSGCODFnEOeda0i9cqhxBn8bOnvNxUFGlYmed87f7UtW0+E7nq/uKtVw4xuYjRgDMk/8mU0oCPyscAqtHcdo+WWt0+2X3FyWL9Tp0sk5CAwrvA/SfJTS76GkU0IfOaWa3Z6OS76aec4o1upXkg/NxD/l2UvaMfu+qyRiY7mxreLmhs9gPj6lgOIVD8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
